server:
  port: 3000
  servlet:
    context-path: /api

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.0.210:3307/todo_db?characterEncoding=UTF-8&serverTimezone=KST
#    url: jdbc:mariadb://database-1.crdzib85ofw0.us-east-2.rds.amazonaws.com:3306/todo_db?characterEncoding=UTF-8&serverTimezone=KST
    password: Kcnet00!@#$
    username: todo
  jpa:
    generate-ddl: false
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: validate
      use-new-id-generator-mappings: false
    properties:
      hibernate.show_sql: true
      hibernate.format_sql: true
      hibernate.use_sql_comments: true